---
# tasks file for maven

- name: Install software-properties-common
  apt:
   name: software-properties-common
   state: present
  become: yes


- name: Add the WebUpd8 Team Java PPA
  become: yes
  apt_repository:
    repo: ppa:webupd8team/java

- name: Update package repositories
  become: yes
  apt:
    update_cache: yes

- name: Install default JDK
  become: yes
  apt:
    name: default-jdk
    state: present

- name: Download Apache Maven
  become: yes
  get_url:
    url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
    dest: /home/edureka/Downloads/apache-maven-3.9.4-bin.tar.gz


- name: Extract Apache Maven
  become: yes
  command: tar -xzvf /home/edureka/Downloads/apache-maven-3.9.4-bin.tar.gz -C /opt/

- name: Configure alternatives for Maven
  command: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.9.4/bin/mvn 1001
  become: yes  

# - name: Configure alternatives for Maven
#   become: yes
#  command: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.9.4-bin.tar.gz/bin/mvn 1001

...
