---
# tasks file for maven

- name: Install python-software-properties
  become: yes
  apt:
    name: python-software-properties
    state: present

- name: Add the WebUpd8 Team Java PPA
  become: yes
  apt_repository:
    repo: ppa:webupd8team/java

- name: Update package repositories
  become: yes
  apt:
    update_cache: yes

- name: Install default JDK
  become: yes
  apt:
    name: default-jdk
    state: present

- name: Download Apache Maven
  become: yes
  get_url:
    url: http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    dest: /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz

- name: Extract Apache Maven
  become: yes
  command: tar -xzvf /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz -C /opt/

- name: Configure alternatives for Maven
  become: yes
  command: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001

...
