---
systemd:
  unit:
    description: Apache Tomcat Web Application Container
    after: network.target

  service:
    type: forking
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
      - CATALINA_PID=/opt/tomcat/temp/tomcat.pid
      - CATALINA_HOME=/opt/tomcat
      - CATALINA_BASE=/opt/tomcat
      - CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC
      - JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom
    exec_start: /opt/tomcat/bin/startup.sh
    exec_stop: /opt/tomcat/bin/shutdown.sh
    user: tomcat
    group: tomcat
    umask: 0007
    restart_sec: 10
    restart: always

  install:
    wanted_by: multi-user.target
...
