
---
- name: Update package repositories
  apt:
    update_cache: yes
  become: yes

- name: Install default JDK
  apt:
    name: default-jdk
    state: present
  become: yes

- name: Create Tomcat group
  group:
    name: tomcat
  become: yes

- name: Create Tomcat user
  user:
    name: tomcat
    group: tomcat
    shell: /bin/false
    home: /opt/tomcat
  become: yes

- name: Download Apache Tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.93/bin/apache-tomcat-8.5.93.tar.gz
    dest: /tmp/apache-tomcat-8.5.31.tar.gz
  become: yes

- name: Create Tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
  become: yes

- name: Extract Apache Tomcat
  unarchive:
    src: /tmp/apache-tomcat-8.5.31.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: '--strip-components=1'
    owner: tomcat
    group: tomcat
  become: yes

- name: Change group ownership of Tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    group: tomcat
  become: yes

- name: Grant read permission to group for conf directory
  file:
    path: /opt/tomcat/conf
    recurse: yes
    mode: '0750'
    group: tomcat
  become: yes

- name: Grant execute permission to group for conf directory
  file:
    path: /opt/tomcat/conf
    recurse: yes
    mode: '0750'
    group: tomcat
  become: yes

- name: Change ownership of specified directories
  file:
    path: "{{ item }}"
    recurse: yes
    owner: tomcat
    group: tomcat
  loop:
    - /opt/tomcat/webapps/
    - /opt/tomcat/work/
    - /opt/tomcat/temp/
    - /opt/tomcat/logs/
  become: yes

- name: Copy systemd service unit file
  copy:
    src: files/tomcat.service.yml
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd

- name: Ensure Tomcat service is enabled and started
  command: /opt/tomcat/bin/startup.sh
  become: yes


- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Start tomcat
  command: /opt/tomcat/bin/startup.sh
  become: yes

...
